# Generated by Django 4.0.6 on 2022-07-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pqrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(default='', max_length=70)),
                ('nombres_apellidos', models.CharField(default='', max_length=200)),
                ('telefono_fijo', models.CharField(default='', max_length=200)),
                ('celular', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('titulo_pqr', models.CharField(default='', max_length=200)),
                ('descripcion_pqr', models.CharField(default='', max_length=200)),
                ('estado_pqr', models.CharField(default='', max_length=200)),
                ('fecha', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
